### ISSUE TITLE
Unable to compile [Resolved]

### ISSUE THREAD

**Issue by fondation1** [mikeoverbay/Terra#1]
Hello !
If this can help you, I downloaded and tried to compile the sources but I had 2 problems:
1) No reference for "AddressOf frmTanks. next_nation" (line 1009 in file frmMain.vb)
   No reference for "AddressOf frmTanks. prev_nation" (line 1022 in file frmMain.vb)
2) the compilation fails because all 3 files are missing
Ionic.Zip. pdb, Ionic.BZip2. pdb, Ionic.ZLib. pdb
in the directory .\Terra-master\Terra\terra zip.

**Comment by mikeoverbay** [comment]
You will need to find ionic zip and put the files that are missing in the zip folder under the projects folder. You can find the zip software here:

https://archive.codeplex.com/?p=dotnetzip

As far as the missing address pointed to by address of.... I’m lost. You you could try doing a search for those address in the entire solution and see it they show up.

Let me know if you get it compiling.

On Feb 3, 2018, at 8:12 AM, fondation1 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello !
If this can help you, I downloaded and tried to compile the sources but I had 2 problems:

  1.  No reference for "AddressOf frmTanks. next_nation" (line 1009 in file frmMain.vb)
No reference for "AddressOf frmTanks. prev_nation" (line 1022 in file frmMain.vb)
  2.  the compilation fails because all 3 files are missing
Ionic.Zip. pdb, Ionic.BZip2. pdb, Ionic.ZLib. pdb
in the directory .\Terra-master\Terra\terra zip.

**Comment by fondation1** [comment]
Ok, I recompiled "Ionic" and commented lines 1009 and 1022 in frmMain.vb file.
With this, I managed to compile Terra.
No other problems to report ^^^
